name: HangmanDB-Actions
run-name: HangmanDB-Action
on: workflow_dispatch
jobs:
  ping-DB:
    runs-on: ubuntu-latest
    steps:
      - name: Ping DB through app
        run: |
          echo "Starting curl test..." 
          curl -sfL hangman-3x9r.onrenver.com || echo "⚠️ Ping failed!"
          echo "Curl test complete!"
