name: HangmanDB-Actions
run-name: HangmanDB-Action
on: workflow_dispatch
jobs:
  ping-DB:
    runs-on: ubuntu-latest
    steps:
      - name: Ping DB through app
        run: |
          echo "Starting Curl Test..." 
          if ! curl -sfL hangman-3x9r.onrender.com/; then
            echo "⚠️ Ping failed!"
            exit 1
          fi
          echo "Curl Test Completed!"
